### ISSUE TITLE
Bower install uses old versions of Polymer

### ISSUE THREAD

**Issue by jtebert** [philya/font-awesome-polymer-icons#3]
Installing via bower required the installation of various core-\* components, which shouldn't be necessary with Polymer 1.0.

UPDATE: It appears that Bower is still using version 4.2. Could you update it so that version 4.3 is available via Bower?

**Comment by diego-d5000** [comment]
I did a fork and tagged it to install with bower. You can install v4.3.0 of this component by te command:

``` sh
bower install diego-d5000/fontawesome-iconset#~4.3.0
```

**Comment by jtebert** [comment]
Thanks!
